title: Accounting Standards for Statutory Boards
url: https://www.assb.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#005373"
  secondary-color: "#005373"
  media-colors:
    - title: media-color-one
      color: "#e5801d"
    - title: media-color-two
      color: "#e5801d"
    - title: media-color-three
      color: "#e5801d"
    - title: media-color-four
      color: "#e5801d"
    - title: media-color-five
      color: "#e5801d"
description: Accounting Standards for Statutory Boards of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d35yvikdo8upn9.amplifyapp.com
prod: https://master.d35yvikdo8upn9.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: news
